import { Role } from '@prisma/client';
import { DataSetDefinition, DataSetKey } from './data-exchange.types';

const admin = [Role.SUPER_ADMIN, Role.ADMIN] as const;
const clinical = [Role.SUPER_ADMIN, Role.ADMIN, Role.DOCTOR, Role.SURGEON, Role.MIDWIFE] as const;
const patientDirectory = [
  Role.SUPER_ADMIN,
  Role.ADMIN,
  Role.RECEPTIONIST,
  Role.SECRETARY,
  Role.DOCTOR,
  Role.SURGEON,
  Role.MIDWIFE,
  Role.MEDICAL_BIOLOGIST,
  Role.RADIOLOGIST,
] as const;
const pharmacy = [Role.SUPER_ADMIN, Role.ADMIN, Role.PHARMACIST, Role.STOREKEEPER] as const;
const billing = [
  Role.SUPER_ADMIN,
  Role.ADMIN,
  Role.RECEPTIONIST,
  Role.SECRETARY,
  Role.CASHIER,
  Role.ACCOUNTANT,
] as const;
const laboratory = [
  Role.SUPER_ADMIN,
  Role.ADMIN,
  Role.DOCTOR,
  Role.SURGEON,
  Role.MIDWIFE,
  Role.LAB_TECHNICIAN,
  Role.MEDICAL_BIOLOGIST,
] as const;
const hospitalization = [
  Role.SUPER_ADMIN,
  Role.ADMIN,
  Role.DOCTOR,
  Role.SURGEON,
  Role.MIDWIFE,
  Role.NURSE,
  Role.RECEPTIONIST,
  Role.SECRETARY,
] as const;
const reports = [
  Role.SUPER_ADMIN,
  Role.ADMIN,
  Role.ACCOUNTANT,
  Role.HR,
  Role.DOCTOR,
  Role.SURGEON,
  Role.MIDWIFE,
  Role.NURSE,
  Role.LAB_TECHNICIAN,
  Role.MEDICAL_BIOLOGIST,
  Role.RADIOLOGIST,
  Role.PHARMACIST,
  Role.STOREKEEPER,
  Role.RECEPTIONIST,
  Role.SECRETARY,
  Role.CASHIER,
] as const;
const hr = [Role.SUPER_ADMIN, Role.ADMIN, Role.HR] as const;

const definitions: DataSetDefinition[] = [
  {
    key: 'patients',
    label: 'Patients',
    description: 'Registre démographique des patients actifs.',
    exportRoles: patientDirectory,
    importRoles: [Role.SUPER_ADMIN, Role.ADMIN, Role.RECEPTIONIST, Role.SECRETARY],
    importable: true,
    columns: [
      { key: 'medicalRecordNumber', label: 'Numéro dossier', kind: 'string', aliases: ['numero dossier', 'n dossier', 'dossier'] },
      { key: 'lastName', label: 'Nom', kind: 'string', required: true },
      { key: 'postName', label: 'Postnom', kind: 'string' },
      { key: 'firstName', label: 'Prénom', kind: 'string', aliases: ['prenom'] },
      { key: 'sex', label: 'Sexe', kind: 'enum', required: true, values: ['MALE', 'FEMALE'], aliases: ['genre'] },
      { key: 'dateOfBirth', label: 'Date de naissance', kind: 'date', aliases: ['naissance'] },
      { key: 'bloodType', label: 'Groupe sanguin', kind: 'string' },
      { key: 'address', label: 'Adresse', kind: 'string' },
      { key: 'phone', label: 'Téléphone', kind: 'string', aliases: ['telephone'] },
      { key: 'emergencyContact', label: "Contact d'urgence", kind: 'string' },
    ],
    sample: {
      medicalRecordNumber: '',
      lastName: 'MALU',
      postName: 'KASONGO',
      firstName: 'Jean',
      sex: 'MALE',
      dateOfBirth: '1990-05-14',
      bloodType: 'O+',
      address: 'Isiro',
      phone: '+243000000000',
      emergencyContact: '+243000000001',
    },
  },
  {
    key: 'medications',
    label: 'Médicaments et stock central',
    description: 'Catalogue, tarifs et quantités de la pharmacie centrale.',
    exportRoles: [...pharmacy, Role.ACCOUNTANT],
    importRoles: pharmacy,
    importable: true,
    columns: [
      { key: 'code', label: 'Code', kind: 'string', required: true },
      { key: 'name', label: 'Désignation', kind: 'string', required: true, aliases: ['nom', 'medicament'] },
      { key: 'form', label: 'Forme', kind: 'string' },
      { key: 'strength', label: 'Dosage', kind: 'string' },
      { key: 'stockQuantity', label: 'Stock', kind: 'integer', required: true, aliases: ['quantite', 'quantité'] },
      { key: 'minimumStock', label: 'Stock minimum', kind: 'integer', required: true },
      { key: 'unitPrice', label: 'Prix unitaire', kind: 'number', required: true, aliases: ['prix'] },
      { key: 'isActive', label: 'Actif', kind: 'boolean', required: true },
    ],
    sample: {
      code: 'MED-001',
      name: 'Ceftriaxone injection',
      form: 'Ampoule',
      strength: '1 g',
      stockQuantity: 100,
      minimumStock: 20,
      unitPrice: 2500,
      isActive: true,
    },
  },
  {
    key: 'staff',
    label: 'Personnel et comptes',
    description: 'Comptes du personnel et profils professionnels.',
    exportRoles: hr,
    importRoles: hr,
    importable: true,
    columns: [
      { key: 'username', label: "Nom d'utilisateur", kind: 'string', required: true, aliases: ['identifiant'] },
      { key: 'password', label: 'Mot de passe initial', kind: 'string', description: 'Obligatoire uniquement pour un nouveau compte.' },
      { key: 'role', label: 'Rôle', kind: 'enum', required: true, values: ['CASHIER','RECEPTIONIST','SECRETARY','DOCTOR','NURSE','LAB_TECHNICIAN','MEDICAL_BIOLOGIST','RADIOLOGIST','SURGEON','MIDWIFE','PHARMACIST','ACCOUNTANT','STOREKEEPER','HR'] },
      { key: 'lastName', label: 'Nom', kind: 'string', required: true },
      { key: 'postName', label: 'Postnom', kind: 'string' },
      { key: 'firstName', label: 'Prénom', kind: 'string' },
      { key: 'specialty', label: 'Spécialité / service', kind: 'string' },
      { key: 'grade', label: 'Grade', kind: 'string' },
      { key: 'licenseNumber', label: 'Numéro professionnel', kind: 'string' },
      { key: 'educationLevel', label: "Niveau d'études", kind: 'string' },
      { key: 'phone', label: 'Téléphone', kind: 'string' },
      { key: 'address', label: 'Adresse', kind: 'string' },
      { key: 'isActive', label: 'Actif', kind: 'boolean', required: true },
    ],
    sample: {
      username: 'infirmier.01',
      password: 'MotDePasseTemporaire2026!',
      role: 'NURSE',
      lastName: 'BORA',
      postName: '',
      firstName: 'Anne',
      specialty: 'Nursing',
      grade: '',
      licenseNumber: '',
      educationLevel: 'A1',
      phone: '+243000000000',
      address: 'Isiro',
      isActive: true,
    },
  },
  {
    key: 'service-reports',
    label: 'Rapports journaliers des services',
    description: 'Rapports des départements et consommation de médicaments ou consommables.',
    exportRoles: reports,
    importRoles: reports,
    importable: true,
    columns: [
      { key: 'department', label: 'Département', kind: 'string', required: true },
      { key: 'businessDate', label: 'Date', kind: 'date', required: true },
      { key: 'shift', label: 'Garde', kind: 'string', required: true },
      { key: 'newAdmissions', label: 'Nouveaux cas admis', kind: 'integer', required: true },
      { key: 'hospitalized', label: 'Hospitalisés', kind: 'integer', required: true },
      { key: 'ambulatory', label: 'Ambulatoires', kind: 'integer', required: true },
      { key: 'MIH', label: 'MIH', kind: 'integer' },
      { key: 'MIF', label: 'MIF', kind: 'integer' },
      { key: 'PED', label: 'PED', kind: 'integer' },
      { key: 'GO', label: 'G-O', kind: 'integer' },
      { key: 'MATERNITE', label: 'Maternité', kind: 'integer' },
      { key: 'CHIRURGIE', label: 'Chirurgie', kind: 'integer' },
      { key: 'itemName', label: 'Médicament / consommable', kind: 'string', required: true },
      { key: 'unit', label: 'Unité', kind: 'string' },
      { key: 'openingStock', label: "Stock d'entrée", kind: 'integer', required: true },
      { key: 'receivedQuantity', label: 'Reçu', kind: 'integer', required: true },
      { key: 'pendingOrder', label: 'Commande en cours', kind: 'integer', required: true },
      { key: 'usedQuantity', label: 'Utilisé', kind: 'integer', required: true },
      { key: 'returnedQuantity', label: 'Retours', kind: 'integer', required: true },
      { key: 'lostQuantity', label: 'Pertes', kind: 'integer', required: true },
      { key: 'unitCost', label: 'Coût unitaire', kind: 'number' },
      { key: 'observations', label: 'Observations', kind: 'string' },
    ],
    sample: {
      department: 'NURSING', businessDate: '2026-08-02', shift: 'JOUR', newAdmissions: 3,
      hospitalized: 4, ambulatory: 5, MIH: 1, MIF: 2, PED: 1, GO: 0, MATERNITE: 0,
      CHIRURGIE: 0, itemName: 'Ceftriaxone injection', unit: 'ampoule', openingStock: 23,
      receivedQuantity: 15, pendingOrder: 20, usedQuantity: 24, returnedQuantity: 2,
      lostQuantity: 1, unitCost: 2500, observations: '',
    },
  },
  {
    key: 'requisitions',
    label: 'Réquisitions internes',
    description: 'Demandes internes adressées à la pharmacie ou au magasin.',
    exportRoles: reports,
    importRoles: reports,
    importable: true,
    columns: [
      { key: 'group', label: 'Groupe de demande', kind: 'string', required: true, description: 'Même valeur pour toutes les lignes de la même réquisition.' },
      { key: 'department', label: 'Service demandeur', kind: 'string', required: true },
      { key: 'priority', label: 'Priorité', kind: 'enum', required: true, values: ['ROUTINE', 'URGENT', 'CRITICAL'] },
      { key: 'reason', label: 'Motif général', kind: 'string', required: true },
      { key: 'itemName', label: 'Désignation', kind: 'string', required: true },
      { key: 'unit', label: 'Unité', kind: 'string' },
      { key: 'quantityRequested', label: 'Quantité demandée', kind: 'integer', required: true },
      { key: 'observations', label: 'Motif de la ligne', kind: 'string' },
    ],
    sample: {
      group: 'LAB-2026-001', department: 'LABORATOIRE', priority: 'URGENT',
      reason: 'Réapprovisionnement des réactifs', itemName: 'Réactif glycémie', unit: 'boîte',
      quantityRequested: 4, observations: 'Stock presque épuisé',
    },
  },
  {
    key: 'billable-services',
    label: 'Tarifs et catalogue des actes',
    description: 'Consultations, examens, hospitalisation et autres services facturables.',
    exportRoles: [...admin, Role.ACCOUNTANT, Role.CASHIER, Role.MEDICAL_BIOLOGIST],
    importRoles: [Role.SUPER_ADMIN, Role.ADMIN, Role.ACCOUNTANT],
    importable: true,
    columns: [
      { key: 'code', label: 'Code', kind: 'string', required: true },
      { key: 'name', label: 'Désignation', kind: 'string', required: true },
      { key: 'category', label: 'Catégorie', kind: 'string' },
      { key: 'type', label: 'Type', kind: 'enum', required: true, values: ['CONSULTATION','LABORATORY','HOSPITALIZATION','PHARMACY','PROCEDURE','RADIOLOGY','SURGERY','MATERNITY','PEDIATRICS','BLOOD_BANK','OTHER'] },
      { key: 'price', label: 'Prix', kind: 'number', required: true },
      { key: 'requiresPrepayment', label: 'Paiement préalable', kind: 'boolean', required: true },
      { key: 'isActive', label: 'Actif', kind: 'boolean', required: true },
    ],
    sample: { code: 'LAB-NFS', name: 'Numération formule sanguine', category: 'Hématologie', type: 'LABORATORY', price: 15000, requiresPrepayment: true, isActive: true },
  },
  {
    key: 'accounting', label: 'Consolidation comptable', description: 'Valeurs de stock et écarts par département.',
    exportRoles: [Role.SUPER_ADMIN, Role.ADMIN, Role.ACCOUNTANT], importRoles: [], importable: false,
    columns: [
      { key: 'businessDate', label: 'Date', kind: 'date' }, { key: 'department', label: 'Département', kind: 'string' },
      { key: 'shift', label: 'Garde', kind: 'string' }, { key: 'patientCount', label: 'Patients', kind: 'integer' },
      { key: 'openingValue', label: "Valeur d'ouverture", kind: 'number' }, { key: 'receivedValue', label: 'Entrées', kind: 'number' },
      { key: 'returnedValue', label: 'Retours', kind: 'number' }, { key: 'usedValue', label: 'Utilisé', kind: 'number' },
      { key: 'lostValue', label: 'Pertes', kind: 'number' }, { key: 'closingValue', label: 'Clôture', kind: 'number' },
      { key: 'variance', label: 'Écart', kind: 'number' },
    ], sample: {},
  },
  {
    key: 'laboratory', label: 'Laboratoire', description: 'Demandes, résultats et validations des examens.',
    exportRoles: laboratory, importRoles: [], importable: false,
    columns: [
      { key: 'requestedAt', label: 'Date demande', kind: 'date' }, { key: 'medicalRecordNumber', label: 'Numéro dossier', kind: 'string' },
      { key: 'patientName', label: 'Patient', kind: 'string' }, { key: 'type', label: 'Examen', kind: 'string' },
      { key: 'status', label: 'Statut', kind: 'string' }, { key: 'requester', label: 'Médecin demandeur', kind: 'string' },
      { key: 'performer', label: 'Exécutant', kind: 'string' }, { key: 'validator', label: 'Validateur', kind: 'string' },
      { key: 'result', label: 'Résultat', kind: 'string' }, { key: 'observations', label: 'Observations', kind: 'string' },
    ], sample: {},
  },
  {
    key: 'invoices', label: 'Factures et paiements', description: 'Facturation détaillée et montants encaissés.',
    exportRoles: billing, importRoles: [], importable: false,
    columns: [
      { key: 'number', label: 'Numéro facture', kind: 'string' }, { key: 'issuedAt', label: 'Date', kind: 'date' },
      { key: 'medicalRecordNumber', label: 'Numéro dossier', kind: 'string' }, { key: 'patientName', label: 'Patient', kind: 'string' },
      { key: 'status', label: 'Statut', kind: 'string' }, { key: 'description', label: 'Ligne', kind: 'string' },
      { key: 'quantity', label: 'Quantité', kind: 'integer' }, { key: 'unitPrice', label: 'Prix unitaire', kind: 'number' },
      { key: 'lineTotal', label: 'Total ligne', kind: 'number' }, { key: 'invoiceTotal', label: 'Total facture', kind: 'number' },
      { key: 'paidAmount', label: 'Payé', kind: 'number' }, { key: 'balance', label: 'Solde', kind: 'number' },
    ], sample: {},
  },
  {
    key: 'hospitalizations', label: 'Hospitalisations', description: 'Admissions, lits, médecins et sorties.',
    exportRoles: hospitalization, importRoles: [], importable: false,
    columns: [
      { key: 'medicalRecordNumber', label: 'Numéro dossier', kind: 'string' }, { key: 'patientName', label: 'Patient', kind: 'string' },
      { key: 'doctor', label: 'Médecin', kind: 'string' }, { key: 'room', label: 'Chambre', kind: 'string' },
      { key: 'bed', label: 'Lit', kind: 'string' }, { key: 'reason', label: 'Motif', kind: 'string' },
      { key: 'status', label: 'Statut', kind: 'string' }, { key: 'admittedAt', label: 'Admission', kind: 'date' },
      { key: 'expectedDischargeAt', label: 'Sortie prévue', kind: 'date' }, { key: 'dischargedAt', label: 'Sortie réelle', kind: 'date' },
    ], sample: {},
  },
  {
    key: 'appointments', label: 'Rendez-vous', description: 'Planning, affectations et étapes du parcours patient.',
    exportRoles: [...patientDirectory, Role.NURSE], importRoles: [], importable: false,
    columns: [
      { key: 'scheduledAt', label: 'Date', kind: 'date' }, { key: 'medicalRecordNumber', label: 'Numéro dossier', kind: 'string' },
      { key: 'patientName', label: 'Patient', kind: 'string' }, { key: 'doctor', label: 'Médecin', kind: 'string' },
      { key: 'service', label: 'Service', kind: 'string' }, { key: 'reason', label: 'Motif', kind: 'string' },
      { key: 'status', label: 'Statut', kind: 'string' }, { key: 'journeyStage', label: 'Étape du parcours', kind: 'string' },
    ], sample: {},
  },
  {
    key: 'consultations', label: 'Consultations', description: 'Consultations, orientations et conclusions médicales.',
    exportRoles: clinical, importRoles: [], importable: false,
    columns: [
      { key: 'createdAt', label: 'Date', kind: 'date' }, { key: 'medicalRecordNumber', label: 'Numéro dossier', kind: 'string' },
      { key: 'patientName', label: 'Patient', kind: 'string' }, { key: 'doctor', label: 'Médecin', kind: 'string' },
      { key: 'status', label: 'Statut', kind: 'string' }, { key: 'reason', label: 'Motif', kind: 'string' },
      { key: 'report', label: 'Rapport', kind: 'string' }, { key: 'orientation', label: 'Orientation', kind: 'string' },
      { key: 'startedAt', label: 'Début', kind: 'date' }, { key: 'completedAt', label: 'Fin', kind: 'date' },
    ], sample: {},
  },
  {
    key: 'prescriptions', label: 'Ordonnances', description: 'Produits internes et achats extérieurs prescrits.',
    exportRoles: [...clinical, Role.PHARMACIST, Role.STOREKEEPER], importRoles: [], importable: false,
    columns: [
      { key: 'number', label: 'Numéro ordonnance', kind: 'string' }, { key: 'issuedAt', label: 'Date', kind: 'date' },
      { key: 'medicalRecordNumber', label: 'Numéro dossier', kind: 'string' }, { key: 'patientName', label: 'Patient', kind: 'string' },
      { key: 'prescriber', label: 'Prescripteur', kind: 'string' }, { key: 'status', label: 'Statut', kind: 'string' },
      { key: 'medicationName', label: 'Médicament', kind: 'string' }, { key: 'availability', label: 'Disponibilité', kind: 'string' },
      { key: 'dosage', label: 'Dosage', kind: 'string' }, { key: 'frequency', label: 'Fréquence', kind: 'string' },
      { key: 'route', label: 'Voie', kind: 'string' }, { key: 'durationDays', label: 'Durée', kind: 'integer' },
      { key: 'quantity', label: 'Quantité', kind: 'integer' }, { key: 'dispensedQuantity', label: 'Délivré', kind: 'integer' },
    ], sample: {},
  },
  {
    key: 'department-stocks', label: 'Stocks des services', description: 'Quantités transférées de la pharmacie vers chaque département.',
    exportRoles: [...reports, Role.ACCOUNTANT], importRoles: [], importable: false,
    columns: [
      { key: 'department', label: 'Département', kind: 'string' }, { key: 'code', label: 'Code produit', kind: 'string' },
      { key: 'medicationName', label: 'Produit', kind: 'string' }, { key: 'quantity', label: 'Quantité', kind: 'integer' },
      { key: 'minimumQuantity', label: 'Minimum', kind: 'integer' }, { key: 'updatedAt', label: 'Mise à jour', kind: 'date' },
    ], sample: {},
  },
];

export const dataSetDefinitions = new Map<DataSetKey, DataSetDefinition>(
  definitions.map((definition) => [definition.key, definition]),
);

export const dataSetKeys = definitions.map((definition) => definition.key);
