<div>
    <link href="css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="home.css"/>
    <link rel='stylesheet prefetch' href='http://cdn.datatables.net/1.10.10/css/dataTables.bootstrap.min.css'>


    <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <?php
    include 'home.php';
    ?>
</div>

<div id="add_data_Modal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h2 class="modal-title">Informations patient</h2>
            </div>
            <div class="modal-body">

                <br/>
                <form method="post" id="insert_form" action="ajouterPatient.php">
                    <h4><b><u>Informations générales :</u></b></h4>
                    <label>Nom</label>
                    <input type="text" name="nom_p" id="nom" class="form-control" />
                    <br/>
                    <label>Postnom</label>
                    <input type="text" name="postnom_p" id="postnom" class="form-control" />
                    <br/>

                    <label>Prénom</label>
                    <input type="text" name="prenom_p" id="prenom" class="form-control" />
                    <br/>

                    <label>Sexe</label>
                    <input type="text" name="sexe" id="sexe" class="form-control"/>
                    <br/>
                    <label>Service</label>
                    <input type="text" name="service" id="service" class="form-control"/>
                    <br/>
                    <label>Poids</label>
                    <input type="text" name="poids" id="poids" class="form-control" />
                    <br/>
                    <label>Température</label>
                    <input type="text" name="temp" id="temp" class="form-control" />
                    <br/>
                    <label>Tension</label>
                    <input type="text" name="tension" id="tension" class="form-control" />
                    <br/>
                    <label>Pathologie</label>
                    <input type="text" name="pathologie" id="pathologie" class="form-control" />
                    <br/>

                    <label>Adresse</label>
                    <textarea name="adresse_p" id="adresse" class="form-control"></textarea>
                    <br/>

                    <label>Téléphone</label>
                    <input type="text" name="numTel_p" id="numTel" class="form-control" />
                    <br/>

                    <label>Date de naissance</label>
                    <input type="date" name="DateNaissance_p" id="dateN" class="form-control"/>
                    <br/>

                    <label>Date de rendez-vous</label>
                    <input type="date" name="DateRdv" id="dateR" class="form-control"/>
                    <br/>


                    <input type="hidden" name="id" id="id" />
                    <input type="submit" name="insert" id="insert" value="Valider" class="btn btn-primary"/>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>

            </div>
        </div>
    </div>
</div>






<div align="center">
    <h2>Liste Patients</h2>
</div>
<div align="right">

    <button type="button" name="ajout" id="ajout" class="btn btn-primary" onclick="$('#add_data_Modal').modal('show');">
        <i class="fa fa-plus"></i>Ajouter</button>
</div>
<br/>
<div class="table-responsive" id="table_patient">

    <table id="autoGeneratedID" role="grid" class="table table-striped table-bordered">
        <thead>
        <tr>
            <th id="idPATIENT" role="gridcell" style="display:none">ID</th>
            <th id="nom_p" role="gridcell">Nom</th>
            <th id="postnom_p" role="gridcell">Postnom</th>
            <th id="prenom_p" role="gridcell">Prénom</th>
            <th id="sexe" role="gridcell">Sexe</th>
            <th id="service" role="gridcell">Service</th>
            <th id="poids" role="gridcell">Poids</th>
            <th id="temp" role="gridcell">Température</th>
            <th id="tension" role="gridcell">Tension</th>
            <th id="pathologie" role="gridcell">Pathologie</th>
            <th id="adresse_p" role="gridcell">Adresse</th>
            <th id="numTel_p" role="gridcell">Téléphone</th>
            <th id="DateNaissance_p" role="gridcell">Date de naissance</th>
            <th id="DateRdv" role="gridcell">Rendez-vous</th>
            <th id="operation">Opération</th>
            <th id="details" >Details</th>

        </tr>
        </thead>
        <tbody>
        <?php
        try{
            $bdd = new PDO('mysql:host=localhost;dbname=service;charset=utf8','root','') ;
        }catch(Exception $e){
            echo "errreur" ;
        }

        $r=$bdd->query('SELECT * FROM patient');
        $row_count = 1;
        while($donne=$r->fetch()){
            ?>
            <tr>

                <td id="idPATIENT" role="gridcell" style="display:none"><?php echo $donne['idPATIENT'];?></td>
                <td id="nom_p" role="gridcell"><?php echo $donne['nom_p'];?></td>
                <td id="postnom_p" role="gridcell"><?php echo $donne['postnom_p'];?></td>
                <td id="prenom_p" role="gridcell"><?php echo $donne['prenom_p'];?></td>
                <td id="sexe" role="gridcell"><?php echo $donne['sexe'];?></td>
                <td id="service" role="gridcell"><?php echo $donne['service'];?></td>
                <td id="poids" role="gridcell"><?php echo $donne['poids'];?></td>
                <td id="temp" role="gridcell"><?php echo $donne['temp'];?></td>
                <td id="tension" role="gridcell"><?php echo $donne['tension'];?></td>
                <td id="pathologie" role="gridcell"><?php echo $donne['pathologie'];?></td>
                <td id="adresse_p" role="gridcell"><?php echo $donne['adresse_p'];?></td>
                <td id="numTel_p" role="gridcell"><?php echo $donne['numTel_p'];?></td>
                <td id="DateNaissance_p" role="gridcell"><?php echo $donne['DateNaissance_p'];?></td>
                <td id="DateRdv" role="gridcell"><?php echo $donne['DateRdv'];?></td>
                
                
                <td>

                    <div class="btn-group">
                        <button type="button"
                                class="btn btn-primary btn-lm dropdown-toggle" data-toggle="dropdown">
                            Action <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">

                            <li><input type="button" name="edit" value="Modifier" id="<?php echo $donne["idPATIENT"];?>"
                                       class="btn btn-warning btn-md edit_data btn-block"/></li>


                            <li><input type="button" name="delete" value="Supprimer" id="<?php echo $donne["idPATIENT"];?>"
                                       class="btn btn-danger btn-md delete_data btn-block"/></li>
                        </ul>
                    </div>


                </td>
               
                <td ><a class="btn btn-info" href="details.php?idp=<?php echo $donne['idPATIENT'];?>">Details</a></td>
            </tr>
            <?php
            $row_count ++ ;
        }
        ?>

        <tbody>
    </table>

</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src='http://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js'></script>
<script src='http://cdn.datatables.net/1.10.10/js/dataTables.bootstrap.min.js'></script>

<script>

    $(document).ready(function(){



        $('#autoGeneratedID').dataTable({
            "columnDefs": [
                { "orderable": false, "targets": 0 }
            ]
        } );
        $('#autoGeneratedID td').attr('role', 'gridcell');
        $('#autoGeneratedID tr').attr('role', 'row');
        $('#autoGeneratedID th').attr('role', 'gridcell');
        $('#autoGeneratedID table').attr('role', 'grid');

    });

    //bouton ajouter

    $('#ajout').click(function () {
        $('#insert').val("Valider");
        $('#insert_form')[0].reset();
    });


    /******************** bouton modifier*********************/

    $(document).on('click', '.edit_data', function () {
        var id = $(this).attr("id");
        $.ajax({
            url: "modierPatient.php",
            method: "POST",
            data: {id: id},
            dataType: "json",
            success: function (data) {
                //remplir les cases avec les anciens données
                $('#nom').val(data.nom_p);
                $('#postnom').val(data.postnom_p);
                $('#prenom').val(data.prenom_p);
                $('#sexe').val(data.sexe);
                $('#service').val(data.service);
                $('#poids').val(data.poids);
                $('#temp').val(data.temp);
                $('#tension').val(data.tension);
                $('#pathologie').val(data.pathologie);
                $('#adresse').val(data.adresse_p);
                $('#numTel').val(data.numTel_p);
                $('#dateN').val(data.DateNaissance_p);
                $('#dateR').val(data.DateRdv);
                $('#debut').val(data.dateD);
                $('#fin').val(data.dateF);
                $('#nlit').val(data.lit);

                $('#id').val(data.idPATIENT);

                $('#insert').val("Modifier");
                $('#add_data_Modal').modal('show');


            }

        });
    });



    /******************************* SUPPRIMER Patient********************/


    $(document).on('click', '.delete_data', function(){
        var id = $(this).attr("id");
        if(confirm("êtes vous sûr de supprimer ce patient?"))
        {
            $.ajax({
                url:"SupprimerPatient.php",
                method:"POST",
                data:{id:id},
                success:function(data){
                    $('#table_patient').html('<div class="alert alert-success">'+data+'</div>');
                    $('#autoGeneratedID').DataTable().destroy();
                    window.location.reload();

                }
            });
            setInterval(function(){
                $('#table_patient').html('');
            }, 5000);
        }
    });



</script>



