const labels: Record<string, string> = {
  SCHEDULED: 'Planifié',
  CHECKED_IN: 'Arrivé',
  COMPLETED: 'Terminé',
  CANCELLED: 'Annulé',
  NO_SHOW: 'Absent',
  WAITING: 'En attente',
  IN_PROGRESS: 'En cours',
  REQUESTED: 'Demandé',
  VALIDATED: 'Validé',
  ACTIVE: 'Actif',
  OPEN: 'Ouvert',
  CLOSED: 'Clôturé',
  DEFAULTED: 'Échéancier en défaut',
  OVERDUE: 'En retard',
  MISSED: 'Non réalisé',
  ADMINISTERED: 'Administré',
  REFUSED: 'Refusé par le patient',
  OMITTED: 'Omis avec justification',
  AUTO_APPROVED: 'Autorisé automatiquement',
  PENDING_DOCTOR: 'Confirmation médicale attendue',
  DISCHARGED: 'Sorti',
  TRANSFERRED: 'Transféré',
  DRAFT: 'Brouillon',
  PENDING: 'À payer',
  PENDING_PAYMENT: 'Paiement attendu',
  PARTIALLY_PAID: 'Paiement partiel',
  PAID: 'Payé',
  AVAILABLE: 'Disponible',
  BUSY: 'Occupé',
  UNKNOWN: 'Disponibilité à confirmer',
  OCCUPIED: 'Occupé',
  MAINTENANCE: 'Maintenance',
  AUTHORIZED: 'Paiement validé',
  CONSUMED: 'Autorisation utilisée',
  WAIVED: 'Urgence autorisée',
  RESOLVED: 'Résolu',
  RESERVED: 'Réservé',
  TRANSFUSED: 'Transfusé',
  DISCARDED: 'Écarté',
  EXPIRED: 'Expiré',
  PLANNED: 'Programmé',
  PRESENT: 'Présent',
  ABSENT: 'Absent',
  LATE: 'En retard',
  LEAVE: 'En congé',
  SICK: 'Malade',
  SUBMITTED: 'Soumis',
  APPROVED: 'Approuvé',
  PARTIALLY_APPROVED: 'Partiellement approuvé',
  REJECTED: 'Rejeté',
  ORDERED: 'Commandé',
  PARTIALLY_RECEIVED: 'Partiellement réceptionné',
  RECEIVED: 'Réceptionné',
  RESULT_ENTERED: 'Résultat saisi',
  AWAITING_PAYMENT: 'Paiement attendu',
  WAITING_DOCTOR: 'Salle d’attente',
  IN_CONSULTATION: 'Chez le médecin',
  LABORATORY: 'Au laboratoire',
  RETURN_TO_DOCTOR: 'Retour chez le médecin',
  HOSPITALIZATION: 'Vers l’hospitalisation',
};

export function StatusBadge({ status }: { status: string }) {
  const normalized = status.toLowerCase().replaceAll('_', '-');
  return <span className={`status-badge status-${normalized}`}>{labels[status] ?? status}</span>;
}
